import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ContextProvider from '@/Context/ContextProvider'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">

      <body className={inter.className}>
        <ContextProvider >

        <Navbar />
        {children}
        
        </ContextProvider>

        <footer className='w-full text-center absolute bottom-3 text-white'>Developed by <Link target='_blank' className='underline transition-all duration-200 hover:text-yellow-400' href={'https://www.linkedin.com/in/alejo-fernandez-23821b243/'}>Alejo Fernandez</Link> </footer>
        </body>
    </html>
  )
}
